"""add robots_blocked to scan_runs

Revision ID: 10a15fbb92b1
Revises: 781e28a75b96
Create Date: 2026-08-04 09:34:34.800487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10a15fbb92b1"
down_revision: Union[str, Sequence[str], None] = "781e28a75b96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scan_runs",
        sa.Column("robots_blocked", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scan_runs", "robots_blocked")
    # ### end Alembic commands ###
