"""add confirm_rejected to scan_runs

Revision ID: 781e28a75b96
Revises: 36d4e4799449
Create Date: 2026-08-04 09:15:55.753367

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "781e28a75b96"
down_revision: Union[str, Sequence[str], None] = "36d4e4799449"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scan_runs",
        sa.Column("confirm_rejected", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scan_runs", "confirm_rejected")
    # ### end Alembic commands ###
